ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: false
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: monthly
    skip: []
    submodules: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: end-of-file-fixer
    - id: check-yaml
  # ----- Python formatting -----
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.5.6
  hooks:
    # Run the linter.
    - id: ruff
      args:
      - --quiet
      - --fix
    # Run the formatter.
    - id: ruff-format
- repo: https://github.com/tox-dev/pyproject-fmt
  rev: 2.2.1
  hooks:
  - id: pyproject-fmt
- repo: https://github.com/abravalheri/validate-pyproject
  rev: v0.18
  hooks:
    - id: validate-pyproject
