ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: monthly
    skip: []
    submodules: false
repos:
  # ----- general formatting -----
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
# ----- Python formatting -----
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
    # Run ruff linter.
    - id: ruff-check
      args:
      - --quiet
      - --fix
    # Run ruff formatter.
    - id: ruff-format
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.6.0
    hooks:
    - id: pyproject-fmt
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject
# ----- spellchecking -----
  - repo: https://github.com/codespell-project/codespell/
    rev: v2.4.1
    hooks:
      - id: codespell
        exclude: demo.ipynb
        args:
          - -L ro
