name: pytest
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'weldx_widgets/**'
      - '.github/workflows/pytest.yml'

jobs:
  pytest:
    name: pytest
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        py: ['3.9', '3.10', '3.11', '3.12']
        weldx_version: ['weldx']
        include:
          - os: ubuntu-latest
            py: '3.10'
            weldx_version: 'git+https://github.com/BAMWelDX/weldx.git'
    env:
      WELDX_VERSION: ${{ matrix.weldx_version }}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.py }}

      - uses: actions/cache@v5
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.cfg') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: pip installs
        run: |
          pip install wheel
          pip install $WELDX_VERSION
          pip install -e .[test]

      - name: run pytest
        run: |
          pytest --no-cov-on-fail

      - name: coverage xml (combination is performed by pytest-cov)
        run: coverage xml

      - name: codecov.io
        uses: codecov/codecov-action@v6.0.1

  test-pixi:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - test-py310
          - test-py311
          - test-py312
          - test-py313
          - test-py314
        weldx: [null]
        include:
          - environment: "test-py312"
            weldx: "git+https://github.com/BAMWelDX/weldx.git"
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          environments: ${{ matrix.environment }}
          activate-environment: true
          log-level: vvv

      - name: Install pip
        if: ${{ matrix.weldx != null }}
        run: pixi add pip

      - name: Install weldx
        if: ${{ matrix.weldx != null }}
        run: pixi run -e ${{ matrix.environment }} pip install "${{matrix.weldx}}"

      - run: pixi run --environment ${{ matrix.environment }} test
