name: pytest
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'weldx_widgets/**'
      - '.github/workflows/pytest.yml'

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        environment:
          - test-py310
          - test-py311
          - test-py312
          - test-py313
          - test-py314
        weldx: [null, "git+https://github.com/BAMWelDX/weldx.git"]
        include:
          - os: macos-latest
            environment: "test-py312"
            weldx: null
          - os: windows-latest
            environment: "test-py312"
            weldx: null
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: prefix-dev/setup-pixi@v0.10.1
        with:
          pixi-version: v0.77.0
          environments: ${{ matrix.environment }}
          log-level: vvv
          frozen: true

      - name: Install weldx
        if: ${{ matrix.weldx != null }}
        run: pixi run --frozen -e ${{ matrix.environment }} pip install "${{matrix.weldx}}"

      - run: pixi run --frozen --environment ${{ matrix.environment }} test
